services:
    - type: web
      name: field-tracker-api
      runtime: node
      rootDir: backend
      buildCommand: npm install
      startCommand: node server.js
      envVars:
          - key: DB_URL
            sync: false
          - key: PORT
            value: 10000
